Add updates to the OS Correct python3 installation for XCP-ng 8.2.1

diff --git a/src/hal/qnap_hal b/src/hal/qnap_hal
--- a/src/hal/qnap_hal
+++ b/src/hal/qnap_hal
@@ -31,10 +31,20 @@
 # https://github.com/guedou/TS-453Be/blob/master/doc/fan_control.md#running-qnap-in-a-chroot
 
 qnap_hal_dependencies() {
-  if ! pkg_install "python3" "python3-pip" "python3-devel"; then
+  # == For XCP-ng 8.2.1 ==
+  if ! pkg_install_from updates "python3" "python3-devel"; then
+    logError "Failed to install python3"
+    return 1
+  elif ! pkg_install_from base "python3-pip"; then
     logError "Failed to install python3"
     return 1
   fi
+
+  # == For XCP-ng 8.3 ==
+  # if ! pkg_install "python3" "python3-pip" "python3-devel"; then
+  #   logError "Failed to install python3"
+  #   return 1
+  # fi
 
   if ! pip_install "python-daemon==2.3.2" "portio==0.6.2" "python-dotenv==0.20.0" "pyserial==3.5"; then
     logError "Failed to install required python modules"
diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -39,6 +39,12 @@ setup() {
 }
 
 setup_dependencies() {
+  # Make sure the OS is up to date
+  if ! yum -y update; then
+    logInfo "Failed to update"
+    return 1
+  fi
+
   # Make sure git is installed and configured
   if ! git_install; then
     logInfo "Failed to install git"
@@ -46,12 +52,6 @@ setup_dependencies() {
   fi
   if ! git_configure "${DQ_ROOT}"; then
     logInfo "Failed to configure git"
-    return 1
-  fi
-
-  # Need to update secuity before curl is used
-  if ! yum -y update curl openssl; then
-    logInfo "Failed to update curl and openssl"
     return 1
   fi
 
