Avoid unecessary hal_init

diff --git a/src/hal/qnap_hal b/src/hal/qnap_hal
--- a/src/hal/qnap_hal
+++ b/src/hal/qnap_hal
@@ -106,6 +106,12 @@ qnap_hal_init() {
   local install_root="${BIN_DIR}/hal"
   local cmd=("hal_daemon" "-f")
 
+  # Skip if already initialized once
+if [[ -f "${QN_HAL_INIT_FILE}"]]; then
+    logInfo "HAL already initialized"
+    return ${ret_value}
+  fi
+
   if ! umount "${install_root}/tmp" >/dev/null 2>&1; then
     logWarn "Failed to unmount ${install_root}/tmp"
   fi
@@ -134,7 +140,11 @@ qnap_hal_init() {
     if qnap_hal_invoke "${cmd[@]}"; then
       if sleep 1; then
         if qnap_hal_invoke "${cmd[@]}"; then
-          if ! sleep 10; then
+          if sleep 10; then
+            if ! touch "${QN_HAL_INIT_FILE}"; then
+              logWarn "Failed to create ${QN_HAL_INIT_FILE}"
+            fi
+          else
             logError "Failed to wait for hal_daemon to start"
             ret_value=1
           fi
@@ -182,6 +192,8 @@ qnap_hal_invoke() {
 
   return ${res}
 }
+
+QN_HAL_INIT_FILE="/tmp/qnap_hal_init"
 
 ###########################
 ###### Startup logic ######
diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -78,7 +78,10 @@ setup_host_hardware() {
     return 1
   fi
 
-  # TODO: Configure partitions
+    if ! storage_setup; then
+    logError "Failed to setup storage"
+    return 1
+  fi
 
   # Install drivers for the 10 GBe NIC
   if ! aq113c_install; then
@@ -128,11 +131,6 @@ setup_host_hardware() {
     fi
   fi
   logInfo "PCI passthrough configured"
-
-  if ! storage_setup; then
-    logError "Failed to setup storage"
-    return 1
-  fi
 
   return 0
 }
