Second pass with linters

diff --git a/src/lifecycle/nut_handler b/src/lifecycle/nut_handler
--- a/src/lifecycle/nut_handler
+++ b/src/lifecycle/nut_handler
@@ -19,10 +19,10 @@ nut_main() {
 nut_init() {
   logInfo "Handling a NUT call: ${UP_ARGS[*]}"
 
-  if ! command -v xe &> /dev/null; then
+  if ! command -v xe &>/dev/null; then
     logError "XCP-ng tools not found"
     return 1
-  elif ! res=$(xe host-list name-label="$(hostname)" --minimal); then
+  elif ! res=$(xe host-list name-label="$(hostname || true)" --minimal); then
     logError "Failed to get host"
     return 1
   elif [[ -z "${res}" ]]; then
@@ -41,6 +41,7 @@ nut_init() {
     logError "Failed to load local configuration"
     return 1
   fi
+  # shellcheck disable=SC2154
   if ! config_load "${CONFIG_DIR}/email.env"; then
     logError "Failed to load QNAP configuration"
     return 1
@@ -50,94 +51,96 @@ nut_init() {
 # Handle NUT event
 # As documented by the NOTIFYCMD https://networkupstools.org/docs/man/upsmon.html
 nut_event() {
+  # shellcheck disable=SC2154
   local not_type="${NOTIFYTYPE}"
+  # shellcheck disable=SC2154
   local not_ups="${UPSNAME}"
   local not_msg="${1}"
 
   logInfo "Handling UPS event: ${not_type} (${not_ups}): ${not_msg}"
 
   case "${not_type}" in
-    ONLINE)
-      "${SCHED_CMD}" "$@"
-      if [[ $? -ne 0 ]]; then
-        error "Failed to invoke upssched for ${not_type}"
-      fi
-      notify_event "${not_msg}"
-      "${HOME_BIN}/qhal" beep Online
-      ;;
-    ONBATT)
-      "${SCHED_CMD}" "$@"
-      if [[ $? -ne 0 ]]; then
-        error "Failed to invoke upssched for ${not_type}"
-      fi
-      notify_event "${not_msg}"
-      "${HOME_BIN}/qhal" beep Outage
-      ;;
-    LOWBATT)
-      warn "Battery is critically low: ${not_msg}"
-      notify_event "${not_msg}"
-      ;;
-    FSD)
-      notify_event "${not_msg}"
-      ;;
-    COMMOK)
-      # logTrace "Communication restored with ${not_ups}: ${not_msg}"
-      notify_event "${not_msg}"
-      ;;
-    COMMBAD)
-      notify_event "${not_msg}"
-      ;;
-    SHUTDOWN)
-      notify_event "${not_msg}"
-      ;;
-    REPLBATT)
-      notify_event "${not_msg}"
-      ;;
-    NOCOMM)
-      notify_event "${not_msg}"
-      ;;
-    NOPARENT)
-      notify_event "${not_msg}"
-      ;;
-    CAL)
-      notify_event "${not_msg}"
-      ;;
-    NOTCAL)
-      notify_event "${not_msg}"
-      ;;
-    OFF)
-      notify_event "${not_msg}"
-      ;;
-    NOTOFF)
-      notify_event "${not_msg}"
-      ;;
-    BYPASS)
-      notify_event "${not_msg}"
-      ;;
-    NOTBYPASS)
-      notify_event "${not_msg}"
-      ;;
-    ECO)
-      notify_event "${not_msg}"
-      ;;
-    NOTECO)
-      notify_event "${not_msg}"
-      ;;
-    ALARM)
-      notify_event "${not_msg}"
-      ;;
-    NOTALARM)
-      notify_event "${not_msg}"
-      ;;
-    SUSPEND_STARTING)
-      notify_event "${not_msg}"
-      ;;
-    SUSPEND_FINISHED)
-      notify_event "${not_msg}"
-      ;;
-    *)
-      warn "Unknown UPS event: ${not_type}"
-      ;;
+  ONLINE)
+    if ! "${SCHED_CMD}" "$@"; then
+      error "Failed to invoke upssched for ${not_type}"
+    fi
+    notify_event "${not_msg}"
+    # shellcheck disable=SC2154
+    "${HOME_BIN}/qhal" beep Online
+    ;;
+  ONBATT)
+    if ! "${SCHED_CMD}" "$@"; then
+      error "Failed to invoke upssched for ${not_type}"
+    fi
+    notify_event "${not_msg}"
+    # shellcheck disable=SC2154
+    "${HOME_BIN}/qhal" beep Outage
+    ;;
+  LOWBATT)
+    warn "Battery is critically low: ${not_msg}"
+    notify_event "${not_msg}"
+    ;;
+  FSD)
+    notify_event "${not_msg}"
+    ;;
+  COMMOK)
+    # logTrace "Communication restored with ${not_ups}: ${not_msg}"
+    notify_event "${not_msg}"
+    ;;
+  COMMBAD)
+    notify_event "${not_msg}"
+    ;;
+  SHUTDOWN)
+    notify_event "${not_msg}"
+    ;;
+  REPLBATT)
+    notify_event "${not_msg}"
+    ;;
+  NOCOMM)
+    notify_event "${not_msg}"
+    ;;
+  NOPARENT)
+    notify_event "${not_msg}"
+    ;;
+  CAL)
+    notify_event "${not_msg}"
+    ;;
+  NOTCAL)
+    notify_event "${not_msg}"
+    ;;
+  OFF)
+    notify_event "${not_msg}"
+    ;;
+  NOTOFF)
+    notify_event "${not_msg}"
+    ;;
+  BYPASS)
+    notify_event "${not_msg}"
+    ;;
+  NOTBYPASS)
+    notify_event "${not_msg}"
+    ;;
+  ECO)
+    notify_event "${not_msg}"
+    ;;
+  NOTECO)
+    notify_event "${not_msg}"
+    ;;
+  ALARM)
+    notify_event "${not_msg}"
+    ;;
+  NOTALARM)
+    notify_event "${not_msg}"
+    ;;
+  SUSPEND_STARTING)
+    notify_event "${not_msg}"
+    ;;
+  SUSPEND_FINISHED)
+    notify_event "${not_msg}"
+    ;;
+  *)
+    warn "Unknown UPS event: ${not_type}"
+    ;;
   esac
 }
 
@@ -153,17 +156,17 @@ nut_timer() {
   logInfo "Handling UPS timer: ${timer_name} (${timer_args[*]})"
 
   case "${timer_name}" in
-    earlyshutdown)
-      warn "Triggering an early shutdown"
-      if ! /usr/sbin/upsmon -c fsd; then
-        error "Failed to call a forced shutdown"
-      else
-        logInfo "Forced shutdown called"
-      fi
-      ;;
-    *)
-      warn "Unknown UPS timer: ${timer_name}"
-      ;;
+  earlyshutdown)
+    warn "Triggering an early shutdown"
+    if ! /usr/sbin/upsmon -c fsd; then
+      error "Failed to call a forced shutdown"
+    else
+      logInfo "Forced shutdown called"
+    fi
+    ;;
+  *)
+    warn "Unknown UPS timer: ${timer_name}"
+    ;;
   esac
 }
 
@@ -182,7 +185,7 @@ notify_event() {
 
   # Subject
   UPS_SUB="[${HOSTNAME}] UPS - ${not_type} on ${not_ups}"
-  
+
   # Prepare event message
   if [[ -z "${not_ups}" ]]; then
     UPS_MSG="An unknown UPS"
@@ -195,16 +198,18 @@ notify_event() {
   else
     UPS_MSG="${UPS_MSG} generated a ${not_type} event"
   fi
-  
+
   if [[ -n "${not_msg}" ]]; then
-    UPS_MSG=$(cat <<END
+    UPS_MSG=$(
+      cat <<END
 ${UPS_MSG} with the following message:
 ${not_msg}
 END
-  )
+    )
   fi
 
-  UPS_MSG=$(cat <<END
+  UPS_MSG=$(
+    cat <<END
 ${UPS_MSG}
 
 Subject: ${UPS_SUB}
@@ -217,17 +222,17 @@ UPSNAME: "${not_ups}"
 \$1: "${not_msg}"
 
 List of UPS on this host:
-$(/usr/bin/upsc -L)
+$(/usr/bin/upsc -L || true)
 
-$(for ups in $(/usr/bin/upsc -l); do
-  echo "Data for UPS: ${ups}"
-  echo ""
-  /usr/bin/upsc "${ups}"
-  echo ""
-  echo "Clients for UPS: ${ups}"
-  /usr/bin/upsc -c "${ups}"
-  echo ""
-done)
+$(for ups in $(/usr/bin/upsc -l || true); do
+      echo "Data for UPS: ${ups}"
+      echo ""
+      /usr/bin/upsc "${ups}"
+      echo ""
+      echo "Clients for UPS: ${ups}"
+      /usr/bin/upsc -c "${ups}"
+      echo ""
+    done || true)
 END
   )
 
@@ -238,16 +243,15 @@ Logging a UPS event:
 ${UPS_MSG}
 END
 
-  echo "${UPS_MSG}" | ${MAIL_CMD} -s "${UPS_SUB}" -r "${SENDER}" "${SYSADMIN}"
-  if [[ $? -ne 0 ]]; then
+  # shellcheck disable=SC2154
+  if ! echo "${UPS_MSG}" | ${MAIL_CMD} -s "${UPS_SUB}" -r "${SENDER}" "${SYSADMIN}"; then
     logError "Failed to send UPS email"
   else
     logInfo "UPS email sent succesfully"
   fi
 
   # Send a XCP-ng notification
-  xe message-create name="UPS Event" body="${UPS_SUB}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"
-  if [[ $? -ne 0 ]]; then
+  if ! xe message-create name="UPS Event" body="${UPS_SUB}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
     logError "Failed to send UPS notification to XCP-ng"
   else
     logInfo "UPS notification sent to XCP-ng"
@@ -260,8 +264,7 @@ nut_parse() {
   local long="help"
 
   local opts
-  opts=$(getopt --options ${short} --long ${long} --name "${UP_ME}" -- "${UP_ARGS[@]}")
-  if [[ $? -ne 0 ]]; then
+  if ! opts=$(getopt --options "${short}" --long "${long}" --name "${UP_ME}" -- "${UP_ARGS[@]}"); then
     error "Failed to parse arguments"
     return 1
   fi
@@ -271,19 +274,19 @@ nut_parse() {
   eval set -- "${opts}"
   while true; do
     case "$1" in
-      -h|--help)
-        nut_usage
-        return 0
-        ;;
-      --)
-        shift
-        break
-        ;;
-      *)
-        error "Invalid option: $1"
-        nut_usage
-        return 1
-        ;;
+    -h | --help)
+      nut_usage
+      return 0
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      error "Invalid option: $1"
+      nut_usage
+      return 1
+      ;;
     esac
   done
 
@@ -291,15 +294,15 @@ nut_parse() {
   while [[ $# -gt 0 ]]; do
     if [[ -z ${cmd} ]]; then
       case "$1" in
-        event|timer|shutdown)
-          cmd="${1}"
-          shift
-          ;;
-        *)
-          error "Unknown command: ${1}"
-          nut_usage
-          return 1
-          ;;
+      event | timer | shutdown)
+        cmd="${1}"
+        shift
+        ;;
+      *)
+        error "Unknown command: ${1}"
+        nut_usage
+        return 1
+        ;;
       esac
     elif [[ "${1}" != "--" ]]; then
       cmd_args=("$@")
@@ -312,20 +315,20 @@ nut_parse() {
 
   if [[ -n "${cmd}" ]]; then
     case "${cmd}" in
-      event)
-        nut_event "${cmd_args[@]}"
-        ;;
-      timer)
-        nut_timer "${cmd_args[@]}"
-        ;;
-      shutdown)
-        nut_shutdown "${cmd_args[@]}"
-        ;;
-      *)
-        error "Unknown command: ${cmd}"
-        nut_usage
-        return 1
-        ;;
+    event)
+      nut_event "${cmd_args[@]}"
+      ;;
+    timer)
+      nut_timer "${cmd_args[@]}"
+      ;;
+    shutdown)
+      nut_shutdown "${cmd_args[@]}"
+      ;;
+    *)
+      error "Unknown command: ${cmd}"
+      nut_usage
+      return 1
+      ;;
     esac
   else
     error "No command specified"
@@ -358,8 +361,7 @@ EOF
 info() {
   logInfo "$1"
 
-  xe message-create name="nut_handler" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"
-  if [[ $? -ne 0 ]]; then
+  if ! xe message-create name="nut_handler" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -367,8 +369,7 @@ info() {
 warn() {
   logWarn "$1"
 
-  xe message-create name="nut_handler" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"
-  if [[ $? -ne 0 ]]; then
+  if ! xe message-create name="nut_handler" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -376,8 +377,7 @@ warn() {
 error() {
   logError "$1"
 
-  xe message-create name="nut_handler" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"
-  if [[ $? -ne 0 ]]; then
+  if ! xe message-create name="nut_handler" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -413,10 +413,12 @@ UP_ROOT=$(realpath "${UP_ROOT}/../..")
 
 # Import dependencies
 SETUP_REPO_DIR="${UP_ROOT}/external/setup"
+# shellcheck disable=SC1091
 if ! source "${SETUP_REPO_DIR}/external/slf4.sh/src/slf4.sh"; then
   echo "Failed to import slf4.sh"
   exit 1
 fi
+# shellcheck disable=SC1091
 if ! source "${SETUP_REPO_DIR}/external/config.sh/src/config.sh"; then
   logFatal "Failed to import config.sh"
 fi
