Finish linter fixes

diff --git a/src/lifecycle/nut_handler b/src/lifecycle/nut_handler
--- a/src/lifecycle/nut_handler
+++ b/src/lifecycle/nut_handler
@@ -19,10 +19,8 @@ nut_main() {
 nut_init() {
   logInfo "Handling a NUT call: ${UP_ARGS[*]}"
 
-  if ! command -v xe &>/dev/null; then
-    logError "XCP-ng tools not found"
-    return 1
-  elif ! res=$(xe host-list name-label="$(hostname || true)" --minimal); then
+  local res
+  if ! xe_exec res host-list name-label="$(hostname || true)" --minimal; then
     logError "Failed to get host"
     return 1
   elif [[ -z "${res}" ]]; then
@@ -245,7 +243,7 @@ END
   fi
 
   # Send a XCP-ng notification
-  if ! xe message-create name="UPS Event" body="${UPS_SUB}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="UPS Event" body="${UPS_SUB}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
     logError "Failed to send UPS notification to XCP-ng"
   else
     logInfo "UPS notification sent to XCP-ng"
@@ -355,7 +353,7 @@ EOF
 info() {
   logInfo "$1"
 
-  if ! xe message-create name="nut_handler" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="nut_handler" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -363,7 +361,7 @@ info() {
 warn() {
   logWarn "$1"
 
-  if ! xe message-create name="nut_handler" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="nut_handler" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -371,7 +369,7 @@ warn() {
 error() {
   logError "$1"
 
-  if ! xe message-create name="nut_handler" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="nut_handler" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -423,6 +421,9 @@ fi
 # shellcheck disable=SC1091
 if ! source "${PREFIX:-/usr/local}/lib/config.sh"; then
   logFatal "Failed to import config.sh"
+fi
+if ! source "${UP_ROOT}/external/xapi.sh/src/xe_utils.sh"; then
+  logFatal "Failed to import xe_utils.sh"
 fi
 
 if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
diff --git a/src/lifecycle/shutdown b/src/lifecycle/shutdown
--- a/src/lifecycle/shutdown
+++ b/src/lifecycle/shutdown
@@ -54,10 +54,8 @@ notify_wait_sol() {
 }
 
 shutdown_init() {
-  if ! command -v xe &>/dev/null; then
-    logError "XCP-ng tools not found"
-    return 1
-  elif ! res=$(xe host-list name-label="$(hostname || true)" --minimal); then
+  local res
+  if ! xe_exec res host-list name-label="$(hostname || true)" --minimal; then
     logError "Failed to get host"
     exit 1
   elif [[ -z "${res}" ]]; then
@@ -170,7 +168,7 @@ EOF
 info() {
   logInfo "$1"
 
-  if ! xe message-create name="Shutdown" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="Shutdown" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -178,7 +176,7 @@ info() {
 warn() {
   logWarn "$1"
 
-  if ! xe message-create name="Shutdown" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="Shutdown" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -186,7 +184,7 @@ warn() {
 error() {
   logError "$1"
 
-  if ! xe message-create name="Shutdown" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="Shutdown" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -238,6 +236,9 @@ fi
 # shellcheck disable=SC1094
 if ! source "${SH_ROOT}/src/storage/storage.sh"; then
   logFatal "Failed to import storage.sh"
+fi
+if ! source "${SH_ROOT}/external/xapi.sh/src/xe_utils.sh"; then
+  logFatal "Failed to import xe_utils.sh"
 fi
 
 if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
diff --git a/src/lifecycle/startup b/src/lifecycle/startup
--- a/src/lifecycle/startup
+++ b/src/lifecycle/startup
@@ -46,10 +46,8 @@ hardware_init() {
 }
 
 startup_init() {
-  if ! command -v xe &>/dev/null; then
-    logError "XCP-ng tools not found"
-    return 1
-  elif ! res=$(xe host-list name-label="$(hostname || true)" --minimal); then
+  local res
+  if ! xe_exec res host-list name-label="$(hostname || true)" --minimal; then
     logError "Failed to get host"
     exit 1
   elif [[ -z "${res}" ]]; then
@@ -75,7 +73,7 @@ startup_init() {
 info() {
   logInfo "$1"
 
-  if ! xe message-create name="Startup" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="Startup" body="${1}" priority="${LVL_INFO}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -83,7 +81,7 @@ info() {
 warn() {
   logWarn "$1"
 
-  if ! xe message-create name="Startup" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="Startup" body="${1}" priority="${LVL_WARN}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -91,7 +89,7 @@ warn() {
 error() {
   logError "$1"
 
-  if ! xe message-create name="Startup" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"; then
+  if ! xe_exec null message-create name="Startup" body="${1}" priority="${LVL_ERROR}" host-uuid="${HOST_ID}"; then
     logError "Failed to send notification to XCP-ng"
   fi
 }
@@ -141,6 +139,9 @@ fi
 # shellcheck disable=SC1094
 if ! source "${ST_ROOT}/src/storage/storage.sh"; then
   logFatal "Failed to import storage.sh"
+fi
+if ! source "${ST_ROOT}/external/xapi.sh/src/xe_utils.sh"; then
+  logFatal "Failed to import xe_utils.sh"
 fi
 
 if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
diff --git a/src/raid/smartd b/src/raid/smartd
--- a/src/raid/smartd
+++ b/src/raid/smartd
@@ -42,22 +42,20 @@ sd_configure() {
 # Scripts that handles events generated by smartd
 # (This file was automatically generated during installation)
 
-# Import email configuration
 if ! source "${PREFIX:-/usr/local}/lib/slf4.sh"; then
   echo "Failed to import slf4.sh"
   exit 1
 fi
+if ! source "${SD_ROOT}/external/xapi.sh/src/xe_utils.sh"; then
+  logFatal "Failed to import xe_utils.sh"
+fi
+# Import email configuration
 if ! source "${cfg_email}"; then
   logFatal "Failed to load email configuration"
 fi
 
 SEND_XCP="true"
-if ! command -v xe &>/dev/null; then
-  logError "XCP-ng not detected"
-  SEND_XCP=""
-fi
-
-if ! res=\$(xe host-list name-label=\$(hostname) --minimal); then
+if ! res host-list name-label=\$(hostname) --minimal; then
   logError "Failed to get host"
   SEND_XCP=""
 elif [[ -z "\${res}" ]]; then
@@ -154,7 +152,7 @@ fi
 if [[ -z "\${SEND_XCP}" ]]; then
   logWarn "Skipping XCP-ng notification"
 else
-  xe message-create name="SMART" body="\${SMARTD_MESSAGE}" priority=\$LVL_WARN host-uuid=\${HOST_ID}
+  xe_exec null message-create name="SMART" body="\${SMARTD_MESSAGE}" priority=\$LVL_WARN host-uuid=\${HOST_ID}
   if [[ \$? -ne 0 ]]; then
     logError "Failed to send SMART notification to XCP-ng"
   else
