- Fix a few variables - Add support for plugin startup - Add support for shutdown plugin - Make it a configuration for the different SR names

diff --git a/src/lifecycle/shutdown b/src/lifecycle/shutdown
--- a/src/lifecycle/shutdown
+++ b/src/lifecycle/shutdown
@@ -37,6 +37,9 @@ shutdown_main() {
 }
 
 shutdown_local() {
+  if ! shutdown_plugin; then
+    error "Failed to run plugins"
+  fi
   if ! storage_unmount; then
     error "Failed to unmount storage"
   fi
@@ -55,6 +58,46 @@ notify_wait_sol() {
   : # TODO: Wait on SOL being ready
 }
 
+shutdown_plugin() {
+  # Run all plugins
+  local plugins
+  local exec=()
+
+  if [[ -z "${PLUGIN_DIR}" ]]; then
+    warn "No plugin directory set"
+    return 0
+  fi
+
+  plugins=$(ls -1 "${PLUGIN_DIR}/stop_"*)
+  readarray -t plugins <<<"${plugins[@]}"
+
+  for plugin in "${plugins[@]}"; do
+    # Check if the plugin is executable
+    if [[ -x "${plugin}" ]]; then
+      exec+=("${PLUGIN_DIR}/${plugin}")
+    else
+      logWarn "Plugin ${plugin} is not executable"
+    fi
+  done
+
+  # Execute all plugins
+  local res code
+  for runnable in "${exec[@]}"; do
+    res=$("${runnable}" 2>&1)
+    code=$?
+    if [[ ${code} -ne 0 ]]; then
+      error "Plugin failed (${code}): ${runnable}"
+      logError <<EOF
+Executable ${runnable} returned with: ${code}
+Output:
+${res}"
+EOF
+    fi
+  done
+
+  return 0
+}
+
 shutdown_init() {
   local res
   if ! xe_exec res host-list name-label="$(hostname || true)" --minimal; then
@@ -71,6 +114,9 @@ shutdown_init() {
   # Load configuration
   if ! config_load "${SH_ROOT}/data/local.env"; then
     logError "Failed to load local configuration"
+  fi
+  if [[ -z "${CONFIG_DIR}" ]]; then
+    logError "CONFIG_DIR is not set"
   fi
   if ! config_load "${CONFIG_DIR}/email.env"; then
     logError "Failed to load QNAP configuration"
diff --git a/src/lifecycle/startup b/src/lifecycle/startup
--- a/src/lifecycle/startup
+++ b/src/lifecycle/startup
@@ -13,6 +13,10 @@ startup_main() {
     error "Failed to mount storage"
   fi
 
+  if ! startup_plugin; then
+    error "Failed to start plugins"
+  fi
+
   # Startup complete
   if ! "${HOME_BIN}/qhal" lcd off; then
     error "Failed to turn off LCD"
@@ -22,6 +26,46 @@ startup_main() {
   fi
 
   info "Startup complete"
+  return 0
+}
+
+startup_plugin() {
+  # Start all plugins
+  local plugins
+  local exec=()
+
+  if [[ -z "${PLUGIN_DIR}" ]]; then
+    warn "No plugin directory set"
+    return 0
+  fi
+
+  plugins=$(ls -1 "${PLUGIN_DIR}/start_"*)
+  readarray -t plugins <<<"${plugins[@]}"
+
+  for plugin in "${plugins[@]}"; do
+    # Check if the plugin is executable
+    if [[ -x "${plugin}" ]]; then
+      exec+=("${PLUGIN_DIR}/${plugin}")
+    else
+      logWarn "Plugin ${plugin} is not executable"
+    fi
+  done
+
+  # Execute all plugins
+  local res code
+  for runnable in "${exec[@]}"; do
+    res=$("${runnable}" 2>&1)
+    code=$?
+    if [[ ${code} -ne 0 ]]; then
+      error "Plugin failed (${code}): ${runnable}"
+      logError <<EOF
+Executable ${runnable} returned with: ${code}
+Output:
+${res}"
+EOF
+    fi
+  done
+
   return 0
 }
 
@@ -64,6 +108,9 @@ startup_init() {
   # Load configuration
   if ! config_load "${ST_ROOT}/data/local.env"; then
     logError "Failed to load local configuration"
+  fi
+  if [[ -z "${CONFIG_DIR}" ]]; then
+    logError "CONFIG_DIR is not set"
   fi
   if ! config_load "${CONFIG_DIR}/email.env"; then
     logError "Failed to load QNAP configuration"
@@ -131,7 +178,7 @@ if [[ -z "${PREFIX}" ]]; then
 fi
 
 # Import dependencies
-SETUP_REPO_DIR="${ST_ROOT}/external/setup"
+XAPI_REPO_DIR="${ST_ROOT}/external/xapi.sh"
 # shellcheck disable=SC1091
 if ! source "${PREFIX}/lib/slf4.sh"; then
   echo "Failed to import slf4.sh"
@@ -149,7 +196,8 @@ fi
 if ! source "${ST_ROOT}/src/storage/storage.sh"; then
   logFatal "Failed to import storage.sh"
 fi
-if ! source "${ST_ROOT}/external/xapi.sh/src/xe_utils.sh"; then
+# shellcheck disable=SC1091
+if ! source "${XAPI_REPO_DIR}/src/xe_utils.sh"; then
   logFatal "Failed to import xe_utils.sh"
 fi
 
