Big cleanup of shutdown script. Re-align with SOL

diff --git a/src/lifecycle/shutdown b/src/lifecycle/shutdown
--- a/src/lifecycle/shutdown
+++ b/src/lifecycle/shutdown
@@ -4,11 +4,14 @@
 # Script executed on shutdown to make sure everything happens orderly
 
 shutdown_main() {
+  if ! shutdown_init; then
+    error "Failed to initialize shutdown"
+    return 1
+  fi
+
   logInfo "Shutting down..."
-  shutdown_init
 
   # If we reach here, the system really is going down
-
   if [[ -f "${SHUTDOWN_CMD_FILE}" ]]; then
     SH_CMD=$(cat "${SHUTDOWN_CMD_FILE}")
     rm -f "${SHUTDOWN_CMD_FILE}"
@@ -16,24 +19,29 @@ shutdown_main() {
     SH_CMD="${SHUTDOWN_LOCAL}"
     warn "No shutdown command found. Assuming: ${SH_CMD}"
   fi
+
   if [[ "${SH_CMD}" == "${SHUTDOWN_LOCAL}" ]]; then
     info "Shutting down locally"
     if ! "${HOME_BIN}/qhal" beep Error; then
       logError "Failed to buzz indicating local shutdown"
     fi
-    shutdown_local
+    if ! shutdown_local; then
+      error "Failed to shutdown local"
+      return 1
+    fi
   elif [[ "${SH_CMD}" == "${SHUTDOWN_ALL}" ]]; then
     info "Shutting down all"
     if ! "${HOME_BIN}/qhal" beep Outage; then
       logError "Failed to buzz indicating all shutdown"
     fi
-    shutdown_all
-  else
-    error "Unknown shutdown command: ${SH_CMD}. Perfoming a local shudown only"
-    shutdown_local
+    if ! shutdown_all; then
+      error "Failed to shutdown all"
+      return 1
+    fi
   fi
 
   logInfo "Shutdown complete. Letting the OS handle the rest"
+  return 0
 }
 
 shutdown_local() {
@@ -187,30 +195,59 @@ shutdown_all_local_vms() {
 }
 
 shutdown_init() {
-  local res
-  if ! xe_exec res host-list name-label="$(hostname || true)" --minimal; then
-    logError "Failed to get host"
-  elif [[ -z "${res}" ]]; then
-    logError "Host not found"
-  elif [[ "${res}" == *","* ]]; then
-    logError "Multiple hosts found"
-  else
-    logTrace "Host identified: ${res}"
-    HOST_ID=${res}
+  # Determine BPKG's global prefix
+  if [[ -z "${PREFIX}" ]]; then
+    if [[ $(id -u || true) -eq 0 ]]; then
+      PREFIX="/usr/local"
+    else
+      PREFIX="${HOME}/.local"
+    fi
   fi
 
-  # Load configuration
-  if ! config_load "${SH_ROOT}/data/local.env"; then
-    logError "Failed to load local configuration"
-  fi
-  if [[ -z "${CONFIG_DIR}" ]]; then
+  # Configure logger
+  export LOG_LEVEL=0
+
+  # shellcheck disable=SC1091
+  if ! source "${PREFIX}/lib/slf4.sh"; then
+    echo "Failed to import slf4.sh"
+    return 1
+  elif ! source "${PREFIX}/lib/config.sh"; then
+    logError "Failed to import config.sh"
+    return 1
+  elif ! source "${SH_ROOT}/src/hal/qnap_hal"; then
+    logError "Failed to import qnap_hal"
+    return 1
+  elif ! source "${SH_ROOT}/src/storage/storage.sh"; then
+    logError "Failed to import storage.sh"
+    return 1
+  elif ! config_load "${SH_ROOT}/data/local.env"; then
+    return 1
+  elif [[ -z ${XAPI_DIR} ]]; then
+    logError "XAPI_DIR is not set"
+    return 1
+  elif [[ -z "${CONFIG_DIR}" ]]; then
     logError "CONFIG_DIR is not set"
-  fi
-  if ! config_load "${CONFIG_DIR}/email.env"; then
-    logError "Failed to load QNAP configuration"
+    return 1
+  elif ! config_load "${CONFIG_DIR}/email.env"; then
+    return 1
+  elif ! source "${XAPI_DIR}/src/xe_vm.sh"; then
+    logError "Failed to import xe_vm.sh"
+    return 1
   fi
 
-  sh_parse
+  # Get host ID
+  if ! xe_host_current HOST_ID; then
+    logError "Failed to get host"
+    return 1
+  else
+    logTrace "Host identified: ${HOST_ID}"
+  fi
+
+  if ! sh_parse; then
+    return 1
+  fi
+
+  return 0
 }
 
 # shellcheck disable=SC2120
@@ -266,21 +303,20 @@ sh_parse() {
   if [[ -n "${cmd}" ]]; then
     logInfo "Mark system ${cmd} for shutdown"
     echo "${cmd}" >"${SHUTDOWN_CMD_FILE}"
-    if [[ "${cmd}" == "${SHUTDOWN_ALL}" ]]; then
-      if [[ "${opt}" == "-e" ]]; then
-        logInfo "Trigger the shutdown"
-        if ! /sbin/shutdown -h +0; then
-          error "Failed to trigger shutdown"
-        else
-          logInfo "Shutdown triggered"
-        fi
+    if [[ "${opt}" == "-e" ]]; then
+      logInfo "Trigger the shutdown"
+      if ! /sbin/shutdown -h +0; then
+        error "Failed to trigger shutdown"
       else
-        logInfo "No shutdown triggered."
+        logInfo "Shutdown triggered"
+        exit 0
       fi
+    else
+      logInfo "No shutdown triggered."
     fi
-    # If we were doing some marking, don't process further
-    exit 0
   fi
+
+  return 0
 }
 
 sh_print_usage() {
@@ -330,14 +366,15 @@ SHUTDOWN_CMD_FILE="/tmp/shutdown.cmd"
 SHUTDOWN_LOCAL="local"
 SHUTDOWN_ALL="all"
 
+# Global variables
+HOST_ID=""
+
 # XCP-ng message levels
 LVL_ERROR=1
 LVL_WARN=2
 LVL_INFO=3
-# shellcheck disable=SC2034 # Not used
-LVL_DEBUG=4
-# shellcheck disable=SC2034 # Not used
-LVL_TRACE=5
+# LVL_DEBUG=4
+# LVL_TRACE=5
 
 ###########################
 ###### Startup logic ######
@@ -355,37 +392,6 @@ while [[ -L "${SH_SOURCE}" ]]; do # resolve $SH_SOURCE until the file is no long
 done
 SH_ROOT=$(cd -P "$(dirname "${SH_SOURCE}")" >/dev/null 2>&1 && pwd)
 SH_ROOT=$(realpath "${SH_ROOT}/../..")
-
-# Determine BPKG's global prefix
-if [[ -z "${PREFIX}" ]]; then
-  if [[ $(id -u || true) -eq 0 ]]; then
-    PREFIX="/usr/local"
-  else
-    PREFIX="${HOME}/.local"
-  fi
-fi
-
-# Import dependencies
-# shellcheck disable=SC1091
-if ! source "${PREFIX}/lib/slf4.sh"; then
-  echo "Failed to import slf4.sh"
-  exit 1
-fi
-# shellcheck disable=SC1091
-if ! source "${PREFIX}/lib/config.sh"; then
-  logFatal "Failed to import config.sh"
-fi
-# shellcheck disable=SC1091
-if ! source "${SH_ROOT}/src/hal/qnap_hal"; then
-  logFatal "Failed to import qnap_hal"
-fi
-# shellcheck disable=SC1094
-if ! source "${SH_ROOT}/src/storage/storage.sh"; then
-  logFatal "Failed to import storage.sh"
-fi
-if ! source "${SH_ROOT}/external/xapi.sh/src/xe_utils.sh"; then
-  logFatal "Failed to import xe_utils.sh"
-fi
 
 if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
   # This script was piped
