Executable rework

diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -392,8 +392,8 @@ if ! source "${SETUP_REPO_DIR}/src/nut.sh"; then
   logFatal "Failed to import nut.sh"
 fi
 # shellcheck disable=SC1091
-if ! source "${SETUP_REPO_DIR}/src/netdata.sh"; then
-  logFatal "Failed to import netdata.sh"
+if ! source "${SETUP_REPO_DIR}/src/netdata"; then
+  logFatal "Failed to import netdata"
 fi
 # shellcheck disable=SC1091
 if ! source "${XE_LIB_DIR}/src/xe_network.sh"; then
