Fix latest issue with refactor

diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -76,7 +76,7 @@ setup_host_hardware() {
 
   # Install drivers for the 10 GBe NIC
   if ! aq113c_install; then
-    logInfo "Failed to install AQ113C drivers"
+    logError "Failed to install AQ113C drivers"
     return 1
   fi
 
@@ -297,6 +297,29 @@ local_xcp_config() {
   return 0
 }
 
+external_depends() {
+  if ! command -v bpkg &>/dev/null; then
+    if ! curl -sLo- https://get.bpkg.sh | bash; then
+      echo "Failed to install bpkg"
+      return 1
+    fi
+  fi
+
+  if [[ ! -f "${PREFIX:-/usr/local}/lib/slf4.sh" ]]; then
+    if ! bpkg install -g jeremfg/slf4.sh; then
+      echo "Failed to install slf4.sh"
+      return 1
+    fi
+  fi
+
+  if [[ ! -f "${PREFIX:-/usr/local}/lib/config.sh" ]]; then
+    if ! bpkg install -g jeremfg/config.sh; then
+      echo "Failed to install config.sh"
+      return 1
+    fi
+  fi
+}
+
 # Constants
 AGE_KEY="homeinfra_demers"
 REBOOT_REQUIRED=0
@@ -316,16 +339,20 @@ done
 DQ_ROOT=$(cd -P "$(dirname "${DQ_SOURCE}")" >/dev/null 2>&1 && pwd)
 DQ_ROOT=$(realpath "${DQ_ROOT}/..")
 
+# Instalal external dependencies
+external_depends
+
 # Import dependencies
 SETUP_REPO_DIR="${DQ_ROOT}/external/setup"
 XE_LIB_DIR="${DQ_ROOT}/external/xapi.sh"
+LOG_CONSOLE=1
 # shellcheck disable=SC1091
-if ! source "${SETUP_REPO_DIR}/external/slf4.sh/src/slf4.sh"; then
+if ! source "${PREFIX:-/usr/local}/lib/slf4.sh"; then
   echo "Failed to import slf4.sh"
   exit 1
 fi
 # shellcheck disable=SC1091
-if ! source "${SETUP_REPO_DIR}/external/config.sh/src/config.sh"; then
+if ! source "${PREFIX:-/usr/local}/lib/config.sh"; then
   logFatal "Failed to import config.sh"
 fi
 # shellcheck disable=SC1091
